### ISSUE TITLE
New screenshot for readme

### ISSUE THREAD

**Issue by seeingidog2** [sepulworld/tfsoa#13]
<img width="1324" alt="screen shot 2017-03-14 at 1 13 19 pm" src="https://cloud.githubusercontent.com/assets/26415029/23920602/99a4ae5a-08b8-11e7-9a48-3b05c84d3c3d.png">

**Comment by seeingidog2** [comment]
<img width="1276" alt="screen shot 2017-03-14 at 1 41 49 pm" src="https://cloud.githubusercontent.com/assets/26415029/23921491/1172f844-08bc-11e7-86ff-a5aa7e3a391c.png">

**Comment by seeingidog2** [comment]
<img width="1269" alt="screen shot 2017-03-14 at 1 48 52 pm" src="https://cloud.githubusercontent.com/assets/26415029/23921750/033ff2b2-08bd-11e7-9d78-632edc2c243b.png">

**Comment by seeingidog2** [comment]
<img width="541" alt="screen shot 2017-03-17 at 1 50 20 pm" src="https://cloud.githubusercontent.com/assets/26415029/24062446/d3de1626-0b18-11e7-9b96-2bde9bc79124.png">

**Comment by sepulworld** [comment]
Sweet
